### PR TITLE
Feature/missing clients

### LINKED ISSUE #9: Client CreditNote
https://developers.lexoffice.io/docs/#credit-notes-endpoint

### LINKED ISSUE #10: Client Files
https://developers.lexoffice.io/docs/#files-endpoint

+ documents() Methods from other Endpoint

### LINKED ISSUE #11: Client Profile
https://developers.lexoffice.io/docs/#profile-endpoint

### PR DESCRIPTION
**Pull request by Sysix**
fixes #9, fixes #10, fixes #11

### CODE REVIEW

**Comment by MDevster** [comment]
Hi @Sysix, do you still want to merge this pull-request? Or will the project no longer be actively developed?

**Comment by Sysix** [comment]
Hello @MDevster jeah I want to merge it. But I could'nt test the File Upload atm.
I didnt wanted to merge a broken part :)

**Comment by MDevster** [comment]
I can test this and get back to you.

**Comment by MDevster** [comment]
I get the following error "Server error: `POST https://api.lexoffice.io/v1/files` resulted in a `500 Internal Server Error` response".
On the command line with curl it works. I have to examine this more closely again.

**Comment by MDevster** [comment]
The upload works if I pass a string for boundary in line 97 of BaseClient.php. 
https://github.com/clicksports/lexoffice-php-api/blob/3527aab19e79c4f4aa2c20a1cdf00a72bd7a8a15/src/BaseClient.php#L97

The sha1 string of the MultipartStream class seems not to be allowed.
https://github.com/guzzle/psr7/blob/master/src/MultipartStream.php#L34

It does not matter what I pass as boundary. 
I would simply specify a "--lexoffice--".

`return new MultipartStream($stream, '--lexoffice--');`

**Comment by Sysix** [comment]
Did you test without "--" at the end and start?

According to [RFC1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) the "--" will define the end.
When it's only that problem, I can merge the PR tomorrow with an update :)

**Comment by MDevster** [comment]
It also works without "--" at the end.

**Comment by MDevster** [comment]
Another small error, the boundary must be added to the header https://github.com/clicksports/lexoffice-php-api/pull/13/commits/9b632d1c7c55af47fdf37c011c61d7d316de1746#diff-6efc82222b7448a4dab6eba3898239d394eeaf252f0e317062060ace0d88eb74R44

like `'Content-Type' => 'multipart/form-data; boundary=--lexoffice'`

**Comment by Sysix** [comment]
Thanks you @MDevster for your help. I just released v0.11.0 
https://github.com/clicksports/lexoffice-php-api/releases/tag/v0.11.0

**Pull request merged**
